
var arrMonacoLangEn = [
	"The editor will never be optimized for usage with a Screen Reader.",
	"Controls whether the editor should run in a mode where it is optimized for screen readers.",
	"Controls fading out of unused code.",
	"Controls whether the editor should detect links and make them clickable.",
	"Controls whether the editor should render the inline color decorators and color picker.",
	"Enables the code action lightbulb in the editor.",
	"Controls whether organize imports action should be run on file save.",
	"Code action kinds to be run on save.",
	"Timeout in milliseconds after which the code actions that are run on save are cancelled.",
	"Controls whether the Linux primary clipboard should be supported.",
	"Controls whether the diff editor shows the diff side by side or inline.",
	"Controls whether the diff editor shows changes in leading or trailing whitespace as diffs.",
	"Special handling for large files to disable certain memory intensive features.",
	"Controls whether the diff editor shows +/- indicators for added/removed changes.",
	"Border color of the range limiting the search. The color must not be opaque to not hide underlying decorations.",
	"Highlight below the word for which a hover is shown. The color must not be opaque to not hide underlying decorations.",
	"Background color of the editor hover.",
	"Border color of the editor hover.",
	"Color of active links.",
	"Background color for text that got inserted. The color must not be opaque to not hide underlying decorations.",
	"Background color for text that got removed. The color must not be opaque to not hide underlying decorations.",
	"Outline color for the text that got inserted.",
	"Outline color for text that got removed.",
	"Border color between the two text editors.",
	"Highlight background color of a snippet tabstop.",
	"Highlight border color of a snippet tabstop.",
	"Highlight background color of the final tabstop of a snippet.",
	"Highlight border color of the final stabstop of a snippet.",
	"Overview ruler marker color for find matches. The color must not be opaque to not hide underlying decorations.",
	"Overview ruler marker color for selection highlights. The color must not be opaque to not hide underlying decorations.",
	"Go to &&Definition",
	"Go to &&Type Definition",
	"Go to &&Implementation",
	"Rename Symbol",
	"Trigger Symbol Highlight",
	"Controls the minimal number of visible leading and trailing lines surrounding the cursor. Known as 'scrollOff' or `scrollOffset` in some other editors.",

	"Render last line number when the file ends with a newline.",
	"Controls whether the Find Widget should add extra lines on top of the editor. When true, you can scroll beyond the first line when the Find Widget is visible.",
	"Scrolling speed multiplier when pressing `Alt`.",
	"Always type over closing quotes or brackets.",
	"Type over closing quotes or brackets only if they were automatically inserted.",
	"Never type over closing quotes or brackets.",
	"Controls whether the editor should type over closing quotes or brackets.",
	"Controls whether remembered suggestion selections are shared between multiple workspaces and windows (needs `#editor.suggestSelection#`).",
	"Controls whether to show or hide icons in suggestions.",
	"Controls how many suggestions IntelliSense will show before showing a scrollbar (maximum 15).",
	"Controls whether some suggestion types should be filtered from IntelliSense. A list of suggestion types can be found here: https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions.",
	"When set to `false` IntelliSense never shows `method` suggestions.",
	"When set to `false` IntelliSense never shows `function` suggestions.",
	"When set to `false` IntelliSense never shows `constructor` suggestions.",
	"When set to `false` IntelliSense never shows `field` suggestions.",
	"When set to `false` IntelliSense never shows `variable` suggestions.",
	"When set to `false` IntelliSense never shows `class` suggestions.",
	"When set to `false` IntelliSense never shows `struct` suggestions.",
	"When set to `false` IntelliSense never shows `interface` suggestions.",
	"When set to `false` IntelliSense never shows `module` suggestions.",
	"When set to `false` IntelliSense never shows `property` suggestions.",
	"When set to `false` IntelliSense never shows `event` suggestions.",
	"When set to `false` IntelliSense never shows `operator` suggestions.",
	"When set to `false` IntelliSense never shows `unit` suggestions.",
	"When set to `false` IntelliSense never shows `value` suggestions.",
	"When set to `false` IntelliSense never shows `constant` suggestions.",
	"When set to `false` IntelliSense never shows `enum` suggestions.",
	"When set to `false` IntelliSense never shows `enumMember` suggestions.",
	"When set to `false` IntelliSense never shows `keyword` suggestions.",
	"When set to `false` IntelliSense never shows `text` suggestions.",
	"When set to `false` IntelliSense never shows `color` suggestions.",
	"When set to `false` IntelliSense never shows `file` suggestions.",
	"When set to `false` IntelliSense never shows `reference` suggestions.",
	"When set to `false` IntelliSense never shows `customcolor` suggestions.",
	"When set to `false` IntelliSense never shows `folder` suggestions.",
	"When set to `false` IntelliSense never shows `typeParameter` suggestions.",
	"When set to `false` IntelliSense never shows `snippet` suggestions.",
	"Controls the behavior of 'Go To' commands, like Go To Definition, when multiple target locations exist.",
	"Show peek view of the results (default)",
	"Go to the primary result and show a peek view",
	"Go to the primary result and enable peek-less navigation to others",
	"Controls whether the editor should highlight matches similar to the selection.",
	"Controls whether the smooth caret animation should be enabled.",
	"Render whitespace characters only on selected text.",
	"Controls whether the editor shows CodeLens.",
	"Controls whether the editor has code folding enabled.",
	"Lines above this length will not be tokenized for performance reasons",
	"Controls whether auto fix action should be run on file save.",
	"Background color of activated options in input fields.",
	"Background color of the type filter widget in lists and trees.",
	"Outline color of the type filter widget in lists and trees.",
	"Outline color of the type filter widget in lists and trees, when there are no matches.",
	"Tree stroke color for the indentation guides.",
	"Border color of error boxes in the editor.",
	"Border color of warning boxes in the editor.",
	"Border color of info boxes in the editor.",
	"Border color of hint boxes in the editor.",
	"Foreground color of editor widgets, such as find/replace.",
	"Color of the selection in an inactive editor. The color must not be opaque so as not to hide underlying decorations.",
	"Color for regions with the same content as the selection. The color must not be opaque so as not to hide underlying decorations.",
	"Color of the other search matches. The color must not be opaque so as not to hide underlying decorations.",
	"Color of the range limiting the search. The color must not be opaque so as not to hide underlying decorations.",
	"Border color of the range limiting the search. The color must not be opaque so as not to hide underlying decorations.",
	"Highlight below the word for which a hover is shown. The color must not be opaque so as not to hide underlying decorations.",
	"Background color of the editor hover status bar.",
	"Background color for text that got inserted. The color must not be opaque so as not to hide underlying decorations.",
	"Background color for text that got removed. The color must not be opaque so as not to hide underlying decorations.",
	"Overview ruler marker color for find matches. The color must not be opaque so as not to hide underlying decorations.",
	"Overview ruler marker color for selection highlights. The color must not be opaque so as not to hide underlying decorations.",
	"Minimap marker color for find matches.",
	"Current Line: {0}. Go to line {1}.",
	"{0}, {1}, commands",
	"Background color of highlighted ranges, like by quick open and find features. The color must not be opaque so as not to hide underlying decorations.",
	"Border color of unnecessary (unused) source code in the editor.",
	"Opacity of unnecessary (unused) source code in the editor. For example, \"#000000c0\" will render the code with 75% opacity. For high contrast themes, use the  'editorUnnecessaryCode.border' theme color to underline unnecessary code instead of fading it out.",
	"Go to &&Bracket",
	"Auto Fix...",
	"Fix All",
	"Preserve Case",
	"Controls whether lists and trees support horizontal scrolling in the workbench.",
	"This setting is deprecated, please use '{0}' instead.",
	"Controls tree indentation in pixels.",
	"Controls whether the tree should render indent guides.",
	"Simple keyboard navigation focuses elements which match the keyboard input. Matching is done only on prefixes.",
	"Highlight keyboard navigation highlights elements which match the keyboard input. Further up and down navigation will traverse only the highlighted elements.",
	"Filter keyboard navigation will filter out and hide all the elements which do not match the keyboard input.",
	"Controls the keyboard navigation style for lists and trees in the workbench. Can be simple, highlight and filter.",
	"Controls whether keyboard navigation in lists and trees is automatically triggered simply by typing. If set to `false`, keyboard navigation is only triggered when executing the `list.toggleKeyboardNavigation` command, for which you can assign a keyboard shortcut.",
	"Go to Declaration",
	"Peek Declaration",
	"Next &&Problem",
	"Previous &&Problem",
	"Transform to Title Case",
	"Add Cursors To Bottom",
	"Add Cursors To Top",
	"Peek References",
	"Expand Selection",
	"Shrink Selection",
	"Background color of a symbol during read-access, like reading a variable. The color must not be opaque so as not to hide underlying decorations.",
	"Background color of a symbol during write-access, like writing to a variable. The color must not be opaque so as not to hide underlying decorations.",
	"Overview ruler marker color for symbol highlights. The color must not be opaque so as not to hide underlying decorations.",
	"Overview ruler marker color for write-access symbol highlights. The color must not be opaque so as not to hide underlying decorations.",
	"Developer: Force Retokenize",
];

var arrMonacoLangZh = [
	"编辑器永远不会为使用屏幕阅读器而优化。",
	"控制编辑器是否应在为屏幕阅读器优化的模式下运行。",
	"控件淡出未使用代码。",
	"控件是否应检测链接并使其可单击。",
	"控件是否应呈现内联颜色装饰器和颜色选择器。",
	"在编辑器中启用代码操作灯泡。",
	"控制是否在文件保存时运行组织导入操作。",
	"要在save上运行的代码操作类型。",
	"超时(以毫秒为单位)之后，在save上运行的代码操作将被取消。",
	"控件是否应支持Linux主剪贴板。",
	"控制差异编辑器是并排显示差异还是内联显示差异。",
	"控件diff编辑器是否将前导空格或尾随空格中的更改显示为差异。",
	"对大文件的特殊处理，以禁用某些内存密集型特性。",
	"控制差异编辑器是否显示添加/删除更改的+/-指示器。",
	"限制搜索范围的边框颜色。颜色不能是不透明的，以不隐藏底层装饰。",
	"高亮显示悬停显示的单词下面。颜色不能是不透明的，以不隐藏底层装饰。",
	"编辑器悬停的背景颜色。",
	"编辑器悬停的边框颜色。",
	"活动链接的颜色。",
	"插入文本的背景颜色。颜色不能是不透明的，以不隐藏底层装饰。",
	"删除文本的背景颜色。颜色不能是不透明的，以不隐藏底层装饰。",
	"插入文本的轮廓颜色。",
	"删除的文本的轮廓颜色。",
	"两个文本编辑器之间的边框颜色。",
	"高亮显示代码片段选项卡的背景颜色。",
	"突出显示代码片段选项卡的边框颜色。",
	"突出显示代码片段最后一个选项卡的背景颜色。",
	"突出显示代码片段最后一个稳定站的边框颜色。",
	"用于查找匹配项的标尺标记颜色。颜色不能是不透明的，以不隐藏底层装饰。",
	"用于选择高光的标尺标记颜色。颜色不能是不透明的，以不隐藏底层装饰。",
	"转到 &&定义",
	"转到 &&类型定义",
	"转到 &&实现",
	"重命名符号",
	"触发标志突出",

	"控制光标周围可见的前和后行的最小数量。在其他一些编辑器中称为'scrollOff'或'scrollOffset'。",
	"当文件以换行符结尾时，渲染最后一个行号。",
	"控制'查找小部件'是否应在编辑器顶部添加额外的行。如果为true，则在'查找小组件'可见时，您可以滚动到第一行之外。",
	"按下'Alt'时滚动速度倍增器。",
	"始终键入右引号或方括号。",
	"仅在自动插入右引号或方括号时键入它们。",
	"切勿在右引号或方括号中键入。",
	"控制编辑器应键入右引号还是方括号。",
	"控制是否在多个工作空间和窗口之间共享记住的建议选择（需要`#editor.suggestSelection#`）。",
	"控制是显示还是隐藏建议中的图标。",
	"控制IntelliSense在显示滚动条之前将显示多少建议（最多15条）。",
	"控制是否应从IntelliSense中过滤某些建议类型。可以在此处找到建议类型的列表：https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions。",
	"设置为`false`时，IntelliSense永远不会显示`method`建议。",
	"设置为`false`时，IntelliSense永远不会显示`function`建议。",
	"设置为`false`时，IntelliSense永远不会显示`constructor`的建议。",
	"设置为`false`时，IntelliSense永远不会显示`field`建议。",
	"设置为`false`时，IntelliSense永远不会显示`variable`建议。",
	"设置为`false`时，IntelliSense永远不会显示`class`建议。",
	"设置为`false`时，IntelliSense永远不会显示`struct`建议。",
	"设置为`false`时，IntelliSense永远不会显示`interface`建议。",
	"设置为`false`时，IntelliSense永远不会显示`module`建议。",
	"设置为`false`时，IntelliSense永远不会显示`property`建议。",
	"设置为`false`时，IntelliSense永远不会显示`event`建议。",
	"设置为`false`时，IntelliSense永远不会显示`operator`建议。",
	"设置为`false`时，IntelliSense永远不会显示`unit`建议。",
	"设置为`false`时，IntelliSense永远不会显示`value`建议。",
	"设置为`false`时，IntelliSense永远不会显示`constant`建议。",
	"设置为`false`时，IntelliSense永远不会显示`enum`建议。",
	"设置为`false`时，IntelliSense永远不会显示`enumMember`建议。",
	"设置为`false`时，IntelliSense永远不会显示`keyword`建议。",
	"设置为`false`时，IntelliSense永远不会显示`text`建议。",
	"设置为`false`时，IntelliSense永远不会显示`color`建议。",
	"设置为`false`时，IntelliSense永远不会显示`file`建议。",
	"设置为`false`时，IntelliSense永远不会显示`reference`建议。",
	"设置为`false`时，IntelliSense永远不会显示`customcolor`建议。",
	"设置为`false`时，IntelliSense永远不会显示`folder`建议。",
	"设置为`false`时，IntelliSense永远不会显示`typeParameter`建议。",
	"设置为`false`时，IntelliSense永远不会显示`snippet`建议。",
	"当存在多个目标位置时，控制'转到'命令（如'转到定义'）的行为。",
	"显示结果的浏览视图（默认）",
	"转到主要结果并显示预览视图",
	"转到主要结果，并启用对其他用户的无窥视导航",
	"控制编辑器是否应突出显示与所选内容相似的匹配项。",
	"控制是否应启用平滑的插入符号动画。",
	"仅在选定的文本上呈现空白字符。",
	"控制编辑器是否显示CodeLens。",
	"控制编辑器是否启用了代码折叠。",
	"出于性能原因，超过此长度的行将不会被标记",
	"控制是否应在文件保存上运行自动修复操作。",
	"输入字段中已激活选项的背景颜色。",
	"列表和树中类型过滤器小部件的背景色。",
	"列表和树中类型过滤器小部件的轮廓颜色。",
	"没有匹配项时，列表和树中类型过滤器小部件的轮廓颜色。",
	"缩进指南的树笔触颜色。",
	"编辑器中错误框的边框颜色。",
	"编辑器中警告框的边框颜色。",
	"编辑器中信息框的边框颜色。",
	"编辑器中提示框的边框颜色。",
	"编辑器小部件的前景色，例如查找/替换。",
	"非活动编辑器中所选内容的颜色。颜色必须不透明，以免隐藏基础装饰。",
	"内容与所选内容相同的区域的颜色。颜色必须不透明，以免隐藏基础装饰。",
	"其他搜索匹配项的颜色。颜色必须不透明，以免隐藏基础装饰。",
	"限制搜索范围的颜色。颜色必须不透明，以免隐藏基础装饰。",
	"限制搜索范围的边框颜色。颜色必须不透明，以免隐藏基础装饰。",
	"突出显示要悬停的单词下方。颜色必须不透明，以免隐藏基础装饰。",
	"编辑器悬停状态栏的背景颜色。",
	"插入文字的背景颜色。颜色必须不透明，以免隐藏基础装饰。",
	"被删除的文本的背景色。颜色必须不透明，以免隐藏基础装饰。",
	"概述标尺标记颜色，用于查找匹配项。颜色必须不透明，以免隐藏基础装饰。",
	"选择突出显示的概述标尺标记颜色。颜色必须不透明，以免隐藏基础装饰。",
	"小地图标记颜色，用于查找匹配项。",
	"当前行：{0}。转到第{1}行。",
	"{0}，{1}，命令",
	"突出显示范围的背景颜色，例如通过快速打开和查找功能。颜色必须不透明，以免隐藏基础装饰。",
	"编辑器中不必要（未使用）的源代码的边框颜色。",
	"编辑器中不必要（未使用）的源代码不透明。例如，\"#000000c0\"将使代码具有75％的不透明度。对于高对比度主题，请使用' editorUnnecessaryCode.border'主题颜色在不必要的代码下划线，而不是使其淡出。",
	"转到&& Bracket",
	"自动修复...",
	"全部修复",
	"保留案例",
	"控制列表和树是否在工作台中支持水平滚动。",
	"不建议使用此设置，请改用'{0}'。",
	"控制以像素为单位的树缩进。",
	"控制树是否应呈现缩进参考线。",
	"简单的键盘导航可以使与键盘输入匹配的元素集中。匹配仅在前缀上完成。",
	"高亮键盘导航突出显示与键盘输入匹配的元素。进一步的上下导航将仅遍历突出显示的元素。",
	"过滤键盘导航将过滤并隐藏所有与键盘输入不匹配的元素。",
	"控制工作台中列表和树的键盘导航样式。可以简单，突出显示和过滤。",
	"控制是否仅通过键入即可自动触发列表和树中的键盘导航。如果设置为false，则仅在执行list.toggleKeyboardNavigation命令时触发键盘导航，您可以为其分配键盘快捷键。",
	"前往声明",
	"返回声明",
	"下一个 &&问题",
	"上一个 &&问题",
	"转换为标题大小写",
	"将光标添加到底部",
	"将游标添加到顶部",
	"速查参考",
	"扩展选择",
	"收缩选择",
	"读取访问期间符号的背景颜色，例如读取变量。颜色必须不透明，以免隐藏基础装饰。",
	"写访问期间符号的背景颜色，例如写变量。颜色必须不透明，以免隐藏基础装饰。",
	"符号突出显示的概述标尺标记颜色。颜色必须不透明，以免隐藏基础装饰。",
	"写访问符号突出显示的概述标尺标记颜色。颜色必须不透明，以免隐藏基础装饰。",
	"开发人员：Force Retokenize",
];

var mapMonacoLang = { "zh-cn":{} };
module.exports = mapMonacoLang;

for(var i = 0; i < arrMonacoLangEn.length; ++i){
	mapMonacoLang["zh-cn"][arrMonacoLangEn[i]] = arrMonacoLangZh[i];
}